from enum import Enum

class PKESchemaFeature(Enum):
  PKE="PKE"
  KEYSWITCH="KEYSWITCH"
  PRE="PRE"
  LEVELEDSHE="LEVELEDSHE"
  ADVANCEDSHE="ADVANCEDSHE"
  MULTIPARTY="MULTIPARTY"
  FHE="FHE"
  SCHEMESWITCH="SCHEMESWITCH"
  