class ScalingTechnique:
  FIXEDMANUAL = "FIXEDMANUAL"
  FIXEDAUTO = "FIXEDAUTO"
  FLEXIBLEAUTO = "FLEXIBLEAUTO"
  FLEXIBLEAUTOEXT = "FLEXIBLEAUTOEXT"
  NORESCALE = "NORESCALE"
  INVALID_RS_TECHNIQUE = "INVALID_RS_TECHNIQUE"